[[redirects]]
  from = "https://docs-mbktechstudio.netlify.app/*"
  to = "https://docs.mbktechstudio.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://project.mbktechstudio.com/*"
  to = "https://docs.mbktechstudio.com/:splat"
  status = 301
  force = true
