[[redirects]]
  from = "https://protfolio-mbktechstudio.netlify.app/*"
  to = "https://portfolio.mbktechstudio.com/:splat"
  status = 301
  force = true


[[redirects]]
  from = "https://protfolio.mbktechstudio.com/*"
  to = "https://portfolio.mbktechstudio.com/:splat"
  status = 301
  force = true
